name: ansible
#Line change special char inside quotes
application: "prod \n"


# Creating Objects

server:
  name: my_server
  version: 1.3
  tag: testing


# Creating lists

list:
  - element1
  - element2
  - element3

  #     OR list can be indended in two ways :


lists:
- element1
- element2
- element3

# other way of creating list is like as array

list3: [element1, element2, element3]


# list of objects 

server_objects:
  - name: my_server1
    version: 1.5
    tag: prod
  - name: my_server2
    version: 1.7
    tag: dev


trigger: off

multi_line: |
  first line
  second line
  third line 

single_long_line: >
  this is very very very 
  very very very very very 
  amazinghghvgvjhbjmbjmbjnnnnnnnnnnnnn
  hfyvvvvvvvvvvvvvvvvvg


remote_install_path: /opt/my/app_config

template:
  src: mydemo
  dest: "{{ remote_install_path }}"

